# Generated by Django 3.0.7 on 2020-06-13 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0004_auto_20200613_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Title',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
