# Generated by Django 3.0.7 on 2020-06-13 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0005_post_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Title',
            field=models.CharField(max_length=100),
        ),
    ]
